"""empty message

Revision ID: f9738564160d
Revises: 
Create Date: 2023-02-10 23:49:37.272455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9738564160d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_txt', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('yes_or_no', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('admirer_id', sa.Integer(), nullable=True),
    sa.Column('like_receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admirer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['like_receiver_id'], ['users.id'], )
    )
    op.create_table('matches',
    sa.Column('matched_1', sa.Integer(), nullable=True),
    sa.Column('matched_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matched_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matched_2'], ['users.id'], )
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('sexual_orientation', sa.String(length=50), nullable=False),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('political_affiliation', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('kids', sa.String(length=50), nullable=True),
    sa.Column('pets', sa.String(length=50), nullable=True),
    sa.Column('diet', sa.String(length=50), nullable=True),
    sa.Column('smoker', sa.String(length=50), nullable=True),
    sa.Column('drinker', sa.String(length=50), nullable=True),
    sa.Column('marijuana', sa.String(length=50), nullable=True),
    sa.Column('zodiac', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.String(length=1000), nullable=False),
    sa.Column('is_profile_pic', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_table('profiles')
    op.drop_table('matches')
    op.drop_table('likes')
    op.drop_table('answers')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
